### ISSUE TITLE
Incompatible with `junegunn/vim-peekaboo`

### ISSUE THREAD

**Issue by xu-cheng** [hecal3/vim-leader-guide#25]
With `junegunn/vim-peekaboo` installed along side with this plugin, pressing new key in the guide window will fail to trigger the proper command or the completion. Instead it will insert characters from the clipboard.

**Comment by hecal3** [comment]
What operating system do you use?
What is the output if you run
`:echo v:register`

The issue is related to the register passthrough.
When leader guide appears after calling a register, it will be passed to the command you call. And at this point peekaboo appears unwanted.

To avoid passing a register leader guide checks if you actually used one with the variable v:register. Unfortunately this variable apparently has a different default value depending on the os.

**Comment by hecal3** [comment]
Should be fixed

It wasn't actually the os that was the problem but the clipboard settings and some weird corner cases.

**Comment by xu-cheng** [comment]
Unfortunately, it doesn't fully fix the problem for me. Right now, pressing new key in the guide window will trigger proper completion. However, when I want to invoke the command, what I get is the command name is inserted into the buffer. 

Below is an example of what I get when I press <kbd>,</kbd>(my leader key), <kbd>g</kbd>, <kbd>s</kbd>. Instead of invoking `:Gstatus` , I get 
```
tatus
"*: 
```
inserted in the buffer.

![vim](https://cloud.githubusercontent.com/assets/3105373/18866391/45496022-84d2-11e6-96d7-33c9a90587c7.gif)

Also FYI, I use macOS + neovim and `:echo v:register` reports `*`. If there is any other info required for debugging, please let me know.

**Comment by hecal3** [comment]
I believe there is a bug in neovim where v:register is always '"' when first calling it after startup.

Could you try this on your system with no steps in between:
```
1. Start neovim
2. :echo v:register
3. :echo v:register
```

For me the first echo prints `"`, the second one `*` or `+`, depending on the clipboard settings. That doesn't seem right to me.

I pushed a workaround for now, where the register in neovim is always ignored on the first call after startup. It's not ideal but at least it should fix this issue for now.

**Comment by hecal3** [comment]
Apparently it works now.
